id: IC65E964B
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:57:42.282683'
last_modified: '2022-06-18T19:57:42.282696'
parser: null
source_metadata:
  title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-08-19); revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:ཀླུ་གྲུབ། (Gongkar Choede) (ld)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4868
  bases:
    a588:
      title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
      order: 1
      base_file: a588.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
